import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import {ClerkProvider} from "@clerk/nextjs";
import { ThemeProvider } from 'next-themes'


export const metadata: Metadata = {
  title: "Note Pink",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode  }>) {
  return (
      <html lang="en" className={`${GeistSans.variable}`} suppressHydrationWarning>
      <body>
      <ClerkProvider>
        <TRPCReactProvider>
            <ThemeProvider attribute="data-mode">
                {children}
            </ThemeProvider>
        </TRPCReactProvider>
      </ClerkProvider>

      </body>
    </html>
  );
}
